### ISSUE TITLE
 libreadline.so.8: cannot open shared object file:

### ISSUE THREAD

**Issue by danrobi11** [leo-arch/clifm#37] opened 2021-06-23 05:53 UTC
**Describe the bug**

I've installed the `clifm-1.1-x86_64.deb` 
Im trying clifm from EXWM in Emacs (dont know if that part of the issue)

I get this error when I try to launch clifm

```
$ clifm
clifm: error while loading shared libraries: libreadline.so.8: cannot open shared object file: No such file or directory
````

I also have the `libreadline` installed

```
libreadline-dev/stable,now 7.0-5 amd64 [installed,automatic]
  GNU readline and history libraries, development files
```
OS: MX 19.4 (patito feo) x86_64 based Debian GNU/Linux 10 (buster)
SysV init version: 2.96
Kernel: 5.10.0-5mx-amd64

**Comment by leo-arch** [comment] 2021-06-23 06:28
Hi @danrobi11. The problem is that the package you downloaded has been compiled against readline 8, while your readline version is actually 7. If I'm not  wrong, you downloaded the package for `Debian testing` (which uses readline 8). Try downloading the package for [Debian 9](https://download.opensuse.org/repositories/home:/archcrack/Debian_9.0/amd64/clifm_1.1-1_amd64.deb) or [Debian 10](https://download.opensuse.org/repositories/home:/archcrack/Debian_10/amd64/clifm_1.1-1_amd64.deb) (both uses readline 7), and see if that works.

**Comment by danrobi11** [comment] 2021-06-23 06:47
>  Try downloading the package for Debian 9 or Debian 10 (both uses readline 7), and see if that works.

@leo-arch Yes, you're right. I did use some testing and backports libs. I'll revert to stable and will report the result. Thanks!

**Comment by leo-arch** [comment] 2021-06-23 06:50
Great. Just let me know if it worked, so that I can close this issue (or close it yourself).

**Comment by danrobi11** [comment] 2021-06-23 07:29
@leo-arch 

Fresh MXLinux install in virtualbox gives me exact same error output.

Will test with other distro

New edit: Same result with a fresh devuan install

**Comment by leo-arch** [comment] 2021-06-23 12:14
Did you install the Debian 10 package? I've tested the package myself on a Debian 10 machine and it works fine.

**Comment by danrobi11** [comment] 2021-06-23 18:42
> Did you install the Debian 10 package?

No.  MXLinux and Devuan. Both Debian based. If I need to run Debian, just close the issue.

Thanks for your time and support.

**Comment by leo-arch** [comment] 2021-06-23 20:58
You don't need to install Debian. In fact your issue is not related to your OS, but to the package you installed. Briefly, you only need to install the right package. Just delete the package you downloaded and download and install this one: https://download.opensuse.org/repositories/home:/archcrack/Debian_10/amd64/clifm_1.1-1_amd64.deb

**Comment by danrobi11** [comment] 2021-06-24 03:43
@leo-arch 

> you only need to install the right package

Aaaah yes, now its working here with the `clifm_1.1-1_amd64.deb`

I did not see that .deb file in the github release. 

Thank you much for the support. My bad, im a big noob :) closing

**Comment by leo-arch** [comment] 2021-06-24 04:17
Good to know it's working now! Please let us know whatever issue, question or comment you have.

And don't forget to give us a star :wink:

**Closed as completed by leo-arch** 2021-06-24 04:17 UTC
