### ISSUE TITLE
foot, kitty, xterm and alacritty close immediately

### ISSUE THREAD

**Issue by theRoboxx** [leo-arch/CliFM#177] opened 2022-12-03 15:57 UTC
**Describe the bug**
Clifm causes the wayland terminal emulator [foot](https://codeberg.org/dnkl/foot) and others to instantly close on startup.
I already opened an [issue](https://codeberg.org/dnkl/foot/issues/1232#issuecomment-703217) over there and got an answer.

**To Reproduce**
1. Run `foot clifm`, `kitty clifm`, `xterm -e clifm` or `alacritty -e clifm`
2. Terminal closes immediately

**Expected behavior**
The terminal should start and execute clifm without closing instantly.

**Desktop**
 - OS: Manjaro Sway Edition
 - Terminal: foot, kitty, xterm or alacritty
 - CliFM version: 1.8-Otis
 - Installation source: AUR

**Comment by leo-arch** [comment] 2022-12-03 16:23
Hi @theRoboxx. This issue is already solved (see #173). The fix will be released in 1.9 soon. In the meantime, you can install the git version.

**Comment by leo-arch** [comment] 2022-12-03 16:25
Duplicate of #173

**Comment by theRoboxx** [comment] 2022-12-03 16:30
Ok perfect, thank you :+1: .

**Closed as completed** 2022-12-03 16:32 UTC
Labels: duplicate

**Comment by leo-arch** [comment] 2022-12-03 16:39
Btw, I'll take a look at those EIO errors reported by **strace**(1) according the foot maintainer.

**Comment by leo-arch** [comment] 2022-12-04 00:13
Couldn't get any `write` errors via **strace**(1), which I executed as follows (no matter if running **clifm** 1.8 or the latest git version, or if running via Wayland (`foot`) or not):

```sh
strace -v -o /tmp/strace.out -e write clifm
```
Indeed, these errors were coming from `nushell` itself, and not from **clifm**. The OP itself (#176) confirmed that these errors dissapeared when upgrading `nushell` from 0.66.1 to 0.72.0. As stated in the [project's page](https://github.com/nushell/nushell#progress), indeed:

> Nu is under heavy development
