### ISSUE TITLE
only 2 lines with fzftab

### ISSUE THREAD

**Issue by chimay** [leo-arch/CliFM#94] opened 2021-12-22 11:26 UTC
With fzftab activated, only 2 lines of possible completion are shown, regardless of the `--height` option of fzf.

**Comment by leo-arch** [comment] 2021-12-22 12:38
What do you mean exactly by two lines? I need more information to be able to reproduce the issue. What are you completing?

**Comment by chimay** [comment] 2021-12-22 13:46
To be more precise, only half of available choices are visible in the fzf menu, 
even if the total number of choices is small (4 or so).

I don't experience this within zsh.

**Comment by leo-arch** [comment] 2021-12-22 15:03
Are you using CliFM git or stable version? Is some value set in `FZF_DEFAULT_OPTS` environment variable?
Also, are you saying that CliFM's TAB completion via FZF works fine on zsh, or rather that the FZF TAB completion plugin for zsh works as intended?

Sorry for so many questions, but cannot fix anything if it's not reproducible.

**Comment by chimay** [comment] 2021-12-22 15:30
I'm using the git version 88c2dcb.

In zsh, when there is a few matches that take less that the height of the fzf "window", all of these choices are displayed, whereas In clifm, only a part of them is visible. I join two screenshots below.

```
export FZF_DEFAULT_OPTS='
	--exact
	--cycle
	--height=40%
	--min-height=10
	--layout=reverse
	--scroll-off=5
	--hscroll-off=100
	--border
	--margin=5%
	--padding=5%
	--color=bw
	--bind=home:first,end:last
	--bind=alt-j:preview-down,alt-k:preview-up
	--bind=insert:print-query
	--bind=tab:replace-query
	--multi
	--marker=*
	--bind=alt-space:toggle+down,shift-tab:toggle+down
	--bind=alt-a:toggle-all
	--bind=ctrl-s:toggle-sort
	--bind=ctrl-u:end-of-line+unix-line-discard
	'
```

first image is with zsh, second with clifm. Not a big deal, just strange.

![fzf-zsh](https://user-images.githubusercontent.com/1503612/147115946-4839ff71-da37-4353-bdae-3d2ce8adf5c2.jpg)
![fzf-clifm](https://user-images.githubusercontent.com/1503612/147115900-566c199c-297d-48b6-8cb7-3c701118d378.jpg)

**Comment by leo-arch** [comment] 2021-12-22 15:45
Great. Issue reproduced. The thing is due to some value in `FZF_DEAFULT_OPTS`. Let me take a look at it.

**Comment by leo-arch** [comment] 2021-12-22 19:03
Well, give it a try now @chimay. It should be working fine.

**Comment by chimay** [comment] 2021-12-22 19:29
it's working, thanks !

**Comment by leo-arch** [comment] 2021-12-22 19:37
Thank you for reporting this bug. Closing.

**Closed as completed** 2021-12-22 19:38 UTC
Labels: bug, solved
